python exp_data.py -gpl -f data/final_depol_alpha100.npz --parallelize --alpha 1.0
python exp_data.py -gpl -f data/final_depol_alpha144.npz --parallelize --alpha 1.44
python exp_data.py -gpl -f data/final_depol_alpha189.npz --parallelize --alpha 1.89
python exp_data.py -gpl -f data/final_depol_alpha233.npz --parallelize --alpha 2.33
python exp_data.py -gpl -f data/final_depol_alpha278.npz --parallelize --alpha 2.78
python exp_data.py -gpl -f data/final_depol_alpha322.npz --parallelize --alpha 3.22
python exp_data.py -gpl -f data/final_depol_alpha367.npz --parallelize --alpha 3.67
python exp_data.py -gpl -f data/final_depol_alpha411.npz --parallelize --alpha 4.11
python exp_data.py -gpl -f data/final_depol_alpha455.npz --parallelize --alpha 4.56
python exp_data.py -gpl -f data/final_depol_alpha500.npz --parallelize --alpha 5.0
